### ISSUE TITLE
HP 0 で開始すると主人公が非表示

### ISSUE THREAD

**Issue by Reputeless** [hackforplay/common#56]
```js
rule.つくられたとき(async function() {
	Player.set(this)
	await this.costume('ゆうしゃ男') // 見た目をきめる
	this.family = ('▼ なかま', Family.プレイヤー) // なかまをきめる
	this.n('たいりょく', ('▼ を', 'イコール'), 0) // 体力をきめる
	this.n('こうげきりょく', ('▼ を', 'イコール'), 1) // こうげき力をきめる

	/*+ つくられたとき */
})

rule.たおされたとき(async function() {
	//Hack.gameover() // ゲームオーバー

	/*+ たおされたとき */
})
```

![image](https://user-images.githubusercontent.com/3108136/74008739-f7523900-49c4-11ea-9772-d25bf1ae7de6.png)

**Comment by teramotodaiki** [comment]
これは体力が０になってキャラクターが destroy されているためです。非表示ではなく、プレイヤーは存在していません。通常はゲームオーバーになるので、ユーザーにとっては意図した動作になるはずです。
特に問題ない動作だと思うので、この Issue は Close します。もし期待した動作が他にあれば、いつでも追記してください @Reputeless
