### ISSUE TITLE
セリフが < や > を含むとバグる

### ISSUE THREAD

**Issue by Reputeless** [hackforplay/common#59]
プレイヤーの中身
```js
rule.つくられたとき(async function() {
	Player.set(this)
	await this.costume('ゆうしゃ男') // 見た目をきめる
	this.family = ('▼ なかま', Family.プレイヤー) // なかまをきめる
	this.n('たいりょく', ('▼ を', 'イコール'), 3) // 体力をきめる
	this.n('こうげきりょく', ('▼ を', 'イコール'), 1) // こうげき力をきめる

	/*+ つくられたとき */

	await this.talk('おはよう><') ///////////////////////////////
})
```
![image](https://user-images.githubusercontent.com/3108136/74009945-a98b0000-49c7-11ea-8eae-f98989f9693e.png)

**Comment by teramotodaiki** [comment]
テキストを XML としてパースしているせいかも知れません
https://github.com/hackforplay/common/blob/7869d728c76583bd9516c570a86ac44cab6092c7/src/hackforplay/ui/textarea.js#L7

本来は文字色やルビなどをサポートするための機能で、パースに失敗した場合は全角の `＞` `＜` に変換しているようです。でも、 `<group></group>` という文字が表示されるのは意図通りではありませんね :(
