### ISSUE TITLE
タマゴが歩きません

### ISSUE THREAD

**Issue by ini-siro** [hackforplay/common#61]
モンスターの卵の「常に」に歩くコードがありますが、
「つくられたとき」にawait this.wait(random(20))があるので歩きません
![スクリーンショット 2020-02-07 18 01 51](https://user-images.githubusercontent.com/38000807/74015511-1906ec80-49d4-11ea-8825-886366e5b630.png)

**Comment by teramotodaiki** [comment]
タマゴは時間が経つと返信し、返信後には普通のキャラクターとして歩き始めるので、そもそも「つねに」の中のコードは必要ないように見えますね

@RyoTaniguchi どう思いますか？

FYI:

アセットについて議論しやすくするために、 [@hackforplay/assets](https://github.com/hackforplay/assets) を public にしました
該当するモンスターのコードはここにあります
https://github.com/hackforplay/assets/blob/a2b7bb6684fb59edca8afbcfaba20a1f44e06fd2/src/assets/%E3%82%BF%E3%83%9E%E3%82%B4/monster_egg-green.js#L28

**Comment by RyoTaniguchi** [comment]
確かに必要ないかな
歩くアニメーションがあるのに、タマゴが棒立ちなのは勿体無いかな？と思って歩かせてただけなので

**Comment by teramotodaiki** [comment]
@RyoTaniguchi なるほど。理解しました 👍 
歩くコードが残っていると誤解を与えるかも知れないので、今は消してもらってもいいですか？

**Comment by RyoTaniguchi** [comment]
＞誤解を与えるかも知れない
同意。消しておきます 👍

**Comment by teramotodaiki** [comment]
https://github.com/hackforplay/assets/compare/a2b7bb6684fb...78ed0354b706

このコミットで修正されたので、 Close します。 @RyoTaniguchi ありがとうございました 👍
